# Generated by Django 2.1 on 2018-08-17 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('vendor', models.CharField(max_length=50)),
                ('isBreakfast', models.BooleanField(verbose_name='Breakfast')),
                ('isLunch', models.BooleanField(verbose_name='Lunch')),
                ('isDinner', models.BooleanField(verbose_name='Dinner')),
                ('isSehri', models.BooleanField(verbose_name='Sehri')),
                ('isAftari', models.BooleanField(verbose_name='Aftari')),
                ('isActive', models.BooleanField(verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('served', 'Served'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('placed', 'Placed')], max_length=15)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_foods', to='home.Employee')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='home.Employee')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodOrder.Food')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Project')),
            ],
        ),
    ]
