# Generated by Django 2.1 on 2018-10-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodOrder', '0002_foodorder_approvaltime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodorder',
            old_name='datetime',
            new_name='orderTime',
        ),
    ]
