# Generated by Django 2.1 on 2018-09-06 13:43

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180829_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFrom', models.DateField(blank=True, null=True, verbose_name='From')),
                ('dateTo', models.DateField(blank=True, null=True, verbose_name='To')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Department')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='code',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dept',
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, upload_to=home.models.rename_photo),
        ),
        migrations.AddField(
            model_name='employeedepartment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='dept',
            field=models.ManyToManyField(blank=True, through='home.EmployeeDepartment', to='home.Department'),
        ),
    ]
