# Generated by Django 2.1 on 2018-09-11 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_employeedesignation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTypeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFrom', models.DateField(auto_now_add=True, null=True, verbose_name='From')),
                ('dateTo', models.DateField(blank=True, null=True, verbose_name='To')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Employee')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.EmployeeType')),
            ],
        ),
    ]
