# Generated by Django 2.1 on 2018-09-11 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_employeetypemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFrom', models.DateField(auto_now_add=True, null=True, verbose_name='From')),
                ('dateTo', models.DateField(blank=True, null=True, verbose_name='To')),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='code',
        ),
        migrations.AddField(
            model_name='employeeperiod',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Employee'),
        ),
    ]
