# Generated by Django 2.1 on 2018-09-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180911_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='joinDate',
        ),
    ]
