# Generated by Django 2.1 on 2018-09-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20180911_1102'),
        ('home', '0009_auto_20180911_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.ManyToManyField(through='home.EmployeeDepartment', to='home.Department'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.ManyToManyField(through='home.EmployeeDesignation', to='home.Designation'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='shift',
        ),
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.ManyToManyField(through='attendance.EmployeeShift', to='attendance.Shift'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='type',
        ),
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.ManyToManyField(through='home.EmployeeTypeMapping', to='home.EmployeeType'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='weekend',
        ),
        migrations.AddField(
            model_name='employee',
            name='weekend',
            field=models.ManyToManyField(through='attendance.EmployeeWeekend', to='attendance.Weekend'),
        ),
        migrations.AlterField(
            model_name='employeeperiod',
            name='dateFrom',
            field=models.DateField(null=True, verbose_name='From'),
        ),
    ]
