# Generated by Django 2.1 on 2018-10-03 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_auto_20180927_1819'),
        ('home', '0011_auto_20180919_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFrom', models.DateField(auto_now_add=True, null=True, verbose_name='From')),
                ('dateTo', models.DateField(blank=True, null=True, verbose_name='To')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Department')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.Shift')),
            ],
        ),
    ]
