# Generated by Django 2.1 on 2018-10-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_auto_20180927_1819'),
        ('home', '0012_departmentshift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='shift',
        ),
        migrations.AddField(
            model_name='department',
            name='shift',
            field=models.ManyToManyField(through='home.DepartmentShift', to='attendance.Shift'),
        ),
    ]
