# Generated by Django 2.1 on 2018-08-17 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('isLate', models.BooleanField(default=False, verbose_name='Is Late?')),
                ('isHalfDay', models.BooleanField(default=False, verbose_name='Is a Half Day?')),
                ('isShortDay', models.BooleanField(default=False, verbose_name='Is a Shot Day?')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DayOfWeekend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inoutId', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('inoutType', models.CharField(choices=[('biometric', 'Biometric'), ('manual', 'Manual'), ('computed', 'Computed'), ('self', 'Self')], default='biometric', max_length=15)),
                ('status', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('approvalDate', models.DateTimeField()),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sickLeave', 'Sick Leave'), ('casualLeave', 'Casual Leave'), ('anualLeave', 'Anual Leave'), ('officialLeave', 'Official Leave'), ('specialLeave', 'Special Leave'), ('hajjLeave', 'Hajj Leave'), ('marriageLeave', 'Marriage Leave'), ('emergencyLeave', 'Emergency Leave'), ('unpaidLeave', 'Unpaid Leave')], max_length=20)),
                ('quotaMax', models.IntegerField(verbose_name='Quota (Max per Year)')),
                ('consecutiveMax', models.IntegerField(verbose_name='Consecutive (Max)')),
                ('consecutiveMin', models.IntegerField(verbose_name='Consecutive (Min)')),
                ('caryForwardable', models.BooleanField(verbose_name='Carry Forwardable')),
                ('onceOnly', models.BooleanField(verbose_name='Once per Employee')),
                ('periodForAdvance', models.IntegerField(verbose_name='Advance Application Period (Days)')),
            ],
        ),
        migrations.CreateModel(
            name='Ramzan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFrom', models.DateField(verbose_name='Starts From')),
                ('dateTo', models.DateField(blank=True, null=True, verbose_name='Ends On')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('timeFrom', models.TimeField()),
                ('timeTo', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Weekend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('days', models.ManyToManyField(through='attendance.DayOfWeekend', to='attendance.Day')),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='weekend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.Weekend'),
        ),
    ]
