# Generated by Django 2.1 on 2018-09-10 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180907_1358'),
        ('attendance', '0002_auto_20180817_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWeekend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFrom', models.DateField(auto_now_add=True, null=True, verbose_name='From')),
                ('dateTo', models.DateField(null=True, verbose_name='To')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Employee')),
                ('weekend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.Weekend')),
            ],
        ),
    ]
