# Generated by Django 2.1 on 2018-09-19 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180919_1319'),
        ('attendance', '0005_auto_20180911_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeFrom', models.TimeField()),
                ('timeTo', models.TimeField()),
                ('isTimeToNextDay', models.BooleanField()),
                ('status', models.CharField(max_length=3)),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.Day')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inTime', models.DateTimeField(null=True)),
                ('outTime', models.DateTimeField(null=True)),
                ('inType', models.CharField(blank=True, max_length=15)),
                ('outType', models.CharField(blank=True, max_length=15)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='dayofweekend',
            name='day',
        ),
        migrations.RemoveField(
            model_name='dayofweekend',
            name='weekend',
        ),
        migrations.RemoveField(
            model_name='employeeweekend',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeweekend',
            name='weekend',
        ),
        migrations.RemoveField(
            model_name='inout',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='weekend',
            name='days',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='isHalfDay',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='isLate',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='isShortDay',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='timeFrom',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='timeTo',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='weekend',
        ),
        migrations.DeleteModel(
            name='DayOfWeekend',
        ),
        migrations.DeleteModel(
            name='EmployeeWeekend',
        ),
        migrations.DeleteModel(
            name='InOut',
        ),
        migrations.DeleteModel(
            name='Weekend',
        ),
        migrations.AddField(
            model_name='dayofshift',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.Shift'),
        ),
        migrations.AddField(
            model_name='shift',
            name='days',
            field=models.ManyToManyField(through='attendance.DayOfShift', to='attendance.Day'),
        ),
    ]
