# Generated by Django 2.1 on 2018-09-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20180919_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayofshift',
            name='isTimeToNextDay',
            field=models.BooleanField(verbose_name='Crossing Day?'),
        ),
        migrations.AlterField(
            model_name='dayofshift',
            name='status',
            field=models.CharField(choices=[('on', 'On'), ('opt', 'Optional')], max_length=3),
        ),
    ]
