# Generated by Django 2.1 on 2018-09-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20180925_1605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ramzan',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='dayofshift',
            name='isTimeToNextDay',
            field=models.BooleanField(default=False, verbose_name='Crossing Date?'),
        ),
        migrations.AlterField(
            model_name='dayofshift',
            name='status',
            field=models.CharField(choices=[('on', 'On'), ('opt', 'Optional'), ('off', 'Off')], max_length=3),
        ),
    ]
