# Generated by Django 2.1 on 2018-10-08 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20181003_1601'),
        ('attendance', '0012_auto_20181008_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='home.Employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvedBy', to='home.Employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leaveType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.LeaveType'),
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='attendance',
        ),
        migrations.AlterUniqueTogether(
            name='leaverequest',
            unique_together={('employee', 'date')},
        ),
    ]
