# Generated by Django 2.1 on 2018-10-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20181003_1601'),
        ('attendance', '0013_auto_20181008_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavetype',
            old_name='quotaMax',
            new_name='quota',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='consecutiveMax',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='consecutiveMin',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
