# Generated by Django 2.1 on 2018-10-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_auto_20181008_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='periodForAdvance',
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='caryForwardable',
            field=models.BooleanField(default=False, verbose_name='Carry Forwardable'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='onceOnly',
            field=models.BooleanField(default=False, verbose_name='Once per Employee'),
        ),
    ]
