# Generated by Django 2.1 on 2018-10-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_auto_20181008_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(choices=[('sickLeave', 'Sick Leave'), ('casualLeave', 'Casual Leave'), ('anualLeave', 'Anual Leave'), ('officialLeave', 'Official Leave'), ('specialLeave', 'Special Leave'), ('hajjLeave', 'Hajj Leave'), ('marriageLeave', 'Marriage Leave'), ('emergencyLeave', 'Emergency Leave'), ('unpaidLeave', 'Unpaid Leave')], max_length=20, unique=True),
        ),
    ]
