# Generated by Django 2.1 on 2018-10-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_auto_20181008_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeshift',
            name='dateTo',
            field=models.DateField(blank=True, null=True, verbose_name='To'),
        ),
        migrations.AlterUniqueTogether(
            name='leaverequest',
            unique_together=set(),
        ),
    ]
